<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ArtAddForm extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        //默认关闭授权,关闭状态会403
        //比如判断一个用户是否有操作权限
        //授权 权限控制
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //规则
            'arts_title'     =>'required|min:2|max:160',
            'arts_desc'   =>'required|min:2|max:160',
            'arts_imgs'      =>'required',
        ];
    }

    public function messages()
    {
        //提示信息
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        //属性
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

    protected function prepareForValidation()
    {
        //在请求验证之前,修改提交的请求数据  强制修改
//        $this->merge([
//            'arts_desc'=>'暂无介绍'
//        ]);
    }
}
